In [19]:
import pandas as pd
df = pd.read_csv("../data/ws/INMET_WS_Stations.csv")
df.head(30)

,Unnamed: 0,DC_NOME,SG_ESTADO,CD_SITUACAO,VL_LATITUDE,VL_LONGITUDE,VL_ALTITUDE,DT_INICIO_OPERACAO,STATION_ID
0,23,ANGRA DOS REIS,RJ,Operante,-22.975556,-44.303333,6,24/08/2017,A628
1,41,ARRAIAL DO CABO,RJ,Operante,-22.975278,-42.021389,5,21/09/2006,A606
2,97,CAMBUCI,RJ,Operante,-21.587500,-41.958333,46,19/11/2002,A604
3,108,CAMPOS DOS GOYTACAZES,RJ,Operante,-21.714722,-41.343889,17,24/09/2006,A607
4,109,CAMPOS DOS GOYTACAZES - SAO TOME,RJ,Operante,-22.041667,-41.051667,7,12/06/2008,A620
5,124,CARMO,RJ,Operante,-21.938745,-42.600936,293,10/10/2018,A629
6,178,DUQUE DE CAXIAS - XEREM,RJ,Operante,-22.589722,-43.282222,22,20/10/2002,A603
7,292,MACAE,RJ,Operante,-22.376111,-41.811944,28,21/09/2006,A608
8,335,NITEROI,RJ,Operante,-22.867500,-43.101944,6,12/07/2018,A627
9,338,NOVA FRIBURGO - SALINAS,RJ,Operante,-22.334722,-42.676944,1070,17/09/2010,A624
10,365,PARATY,RJ,Operante,-23.223611,-44.726944,3,18/11/2006,A619
11,381,PICO DO COUTO,RJ,Operante,-22.464722,-43.291389,1777,21/10/2006,A610
12,413,Paty do Alferes - Avelar,RJ,Operante,-22.347222,-43.417778,508,09/11/2022,A637
13,425,RESENDE,RJ,Operante,-22.451389,-44.445000,"438,83",28/09/2006,A609
14,429,RIO CLARO,RJ,Operante,-22.653579,-44.040916,516,02/06/2016,A626
15,430,RIO DE JANEIRO - FORTE DE COPACABANA,RJ,Operante,-22.988333,-43.190556,"25,59",17/05/2007,A652
16,431,RIO DE JANEIRO - JACAREPAGUA,RJ,Operante,-22.940000,-43.402778,20,09/08/2017,A636
17,432,RIO DE JANEIRO - VILA MILITAR,RJ,Operante,-22.861389,-43.411389,"30,43",12/04/2007,A621
18,433,RIO DE JANEIRO-MARAMBAIA,RJ,Operante,-23.050278,-43.595556,12,07/11/2002,A602
19,458,SANTA MARIA MADALENA,RJ,Operante,-21.950556,-42.010278,517,15/10/2018,A630
20,498,SAQUAREMA - SAMPAIO CORREIA,RJ,Operante,-22.871111,-42.608889,26,01/09/2015,A667
21,501,SEROPEDICA-ECOLOGIA AGRICOLA,RJ,Operante,-22.757778,-43.684722,35,23/05/2000,A601
22,510,SILVA JARDIM,RJ,Operante,-22.645833,-42.415556,19,27/08/2015,A659
23,526,TERESOPOLIS-PARQUE NACIONAL,RJ,Operante,-22.448611,-42.986944,981,31/10/2006,A618
24,535,TRES RIOS,RJ,Operante,-22.098333,-43.208333,295,07/06/2016,A625
25,550,VALENCA,RJ,Operante,-22.358056,-43.695556,370,26/09/2006,A611
26,0,Vidigal,RJ,Operante,-22.992500,-43.233100,NaN,NaN,vidigal
27,10,Irajá,RJ,Operante,-22.826900,-43.336900,NaN,NaN,iraja
28,15,Jardim Botânico,RJ,Operante,-22.972800,-43.223900,NaN,NaN,jardim_botanico
29,18,Barra/Riocentro,RJ,Operante,-22.977200,-43.391600,NaN,NaN,riocentro

In [9]:
from math import radians, sin, cos, sqrt, atan2

def haversine_distance(point1, point2):
    R = 6371  # Earth's radius in kilometers
    lat1, lon1 = point1
    lat2, lon2 = point2
    dlat = radians(lat2 - lat1)
    dlon = radians(lon2 - lon1)
    a = sin(dlat / 2) ** 2 + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ** 2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    distance = R * c
    return distance

def distance_matrix(point, points_list):
    matrix = []
    for p in points_list:
        distance = haversine_distance(point, p)
        matrix.append(distance)
    return matrix

point = (52.2296756, 21.0122287)  # Warsaw, Poland
points_list = [(51.5073509, -0.1277583),  # London, UK
               (40.7127281, -74.0060152),  # New York City, USA
               (48.856614, 2.3522219)]    # Paris, France

matrix = distance_matrix(point, points_list)
print(matrix)  # output: [1464.580386325907, 6698.945740763303, 1319.1667457437978]

[1448.5144720223163, 6854.21376278946, 1366.5493798571713]

In [20]:
A652_Latitude = -22.98833333
A652_Longitude = -43.19055555
A652_point = (A652_Latitude, A652_Longitude)

print("Distances from A652 to all other INMET weather stations located in RJ:")
for index, row in df.iterrows():
    longitude = row['VL_LONGITUDE']
    latitude = row['VL_LATITUDE']
    ws_name = row['DC_NOME']
    ws_id = row['STATION_ID']
    ws_point = (latitude, longitude)
    dist = haversine_distance(A652_point, ws_point)
    print(f"{dist:6.2f}\t {ws_id} - {ws_name}")

Distances from A652 to all other INMET weather stations located in RJ:
113.92	 A628 - ANGRA DOS REIS
119.70	 A606 - ARRAIAL DO CABO
200.84	 A604 - CAMBUCI
236.90	 A607 - CAMPOS DOS GOYTACAZES
243.62	 A620 - CAMPOS DOS GOYTACAZES - SAO TOME
131.50	 A629 - CARMO
 45.31	 A603 - DUQUE DE CAXIAS - XEREM
156.97	 A608 - MACAE
 16.21	 A627 - NITEROI
 89.78	 A624 - NOVA FRIBURGO - SALINAS
159.30	 A619 - PARATY
 59.13	 A610 - PICO DO COUTO
 75.00	 A637 - Paty do Alferes - Avelar
141.84	 A609 - RESENDE
 94.77	 A626 - RIO CLARO
  0.00	 A652 - RIO DE JANEIRO - FORTE DE COPACABANA
 22.38	 A636 - RIO DE JANEIRO - JACAREPAGUA
 26.66	 A621 - RIO DE JANEIRO - VILA MILITAR
 42.02	 A602 - RIO DE JANEIRO-MARAMBAIA
167.40	 A630 - SANTA MARIA MADALENA
 60.98	 A667 - SAQUAREMA - SAMPAIO CORREIA
 56.75	 A601 - SEROPEDICA-ECOLOGIA AGRICOLA
 88.09	 A659 - SILVA JARDIM
 63.54	 A618 - TERESOPOLIS-PARQUE NACIONAL
 98.98	 A625 - TRES RIOS
 87.16	 A611 - VALENCA
  4.38	 vidigal - Vidigal
 23.39	 iraja - Irajá
  3.83	 jardim_botanico - Jardim Botânico
 20.62	 riocentro - Barra/Riocentro
 41.93	 guaratiba - Guaratiba
 51.32	 santa_cruz - Santa Cruz
  9.33	 alto_da_boa_vista - Alto da Boa Vista
 10.68	 sao_cristovao - São Cristóvão

In [23]:
gig_Latitude = -22.809167
gig_Longitude = -43.250556
gig_point = (gig_Latitude, gig_Longitude)

print("Distances from SBGL to INMET weather stations located in RJ:")
for index, row in df.iterrows():
    longitude = row['VL_LONGITUDE']
    latitude = row['VL_LATITUDE']
    ws_name = row['DC_NOME']
    ws_id = row['STATION_ID']
    ws_point = (latitude, longitude)
    dist = haversine_distance(gig_point, ws_point)
    print(f"{dist:6.2f}\t {ws_id} - {ws_name}")

Distances from SBGL to INMET weather stations located in RJ:
109.42	 A628 - ANGRA DOS REIS
127.26	 A606 - ARRAIAL DO CABO
190.14	 A604 - CAMBUCI
230.88	 A607 - CAMPOS DOS GOYTACAZES
241.59	 A620 - CAMPOS DOS GOYTACAZES - SAO TOME
117.60	 A629 - CARMO
 24.62	 A603 - DUQUE DE CAXIAS - XEREM
155.34	 A608 - MACAE
 16.55	 A627 - NITEROI
 79.07	 A624 - NOVA FRIBURGO - SALINAS
157.97	 A619 - PARATY
 38.53	 A610 - PICO DO COUTO
 54.16	 A637 - Paty do Alferes - Avelar
128.88	 A609 - RESENDE
 82.88	 A626 - RIO CLARO
 20.85	 A652 - RIO DE JANEIRO - FORTE DE COPACABANA
 21.33	 A636 - RIO DE JANEIRO - JACAREPAGUA
 17.48	 A621 - RIO DE JANEIRO - VILA MILITAR
 44.35	 A602 - RIO DE JANEIRO-MARAMBAIA
159.30	 A630 - SANTA MARIA MADALENA
 66.12	 A667 - SAQUAREMA - SAMPAIO CORREIA
 44.88	 A601 - SEROPEDICA-ECOLOGIA AGRICOLA
 87.54	 A659 - SILVA JARDIM
 48.37	 A618 - TERESOPOLIS-PARQUE NACIONAL
 79.16	 A625 - TRES RIOS
 67.85	 A611 - VALENCA
 20.46	 vidigal - Vidigal
  9.07	 iraja - Irajá
 18.40	 jardim_botanico - Jardim Botânico
 23.62	 riocentro - Barra/Riocentro
 44.28	 guaratiba - Guaratiba
 45.83	 santa_cruz - Santa Cruz
 17.65	 alto_da_boa_vista - Alto da Boa Vista
 10.17	 sao_cristovao - São Cristóvão

In [ ]:
df[['CD_ESTACAO', 'DC_NOME', 'DT_INICIO_OPERACAO']]

In [ ]:
import pandas as pd
df_A621 = pd.read_csv("../data/ws/A621.csv")
df_A621.info()

In [ ]:
df_A621[df_A621.CHUVA>=5].shape, df_A621[df_A621.CHUVA>=25].shape, df_A621[df_A621.CHUVA>=50].shape